### ISSUE TITLE
Dirhunt can't find a run script in pentest box

### ISSUE THREAD

**Issue by m1m1cat** [Nekmo/dirhunt#41] opened 2018-07-26 14:33 UTC
Pentest box cannot install dirhunt command directly after installing dirhunt, it needs to manually add script to run, and can not find script location.

**Comment by Nekmo** [comment] 2018-07-26 14:54
I think this issue is a duplicate of #36 . Can you check this issue?

**Comment by Nekmo** [comment] 2018-08-11 11:45
Closed due to inactivity.

**Closed by Nekmo** 2018-08-11 11:45 UTC
